name: JUnits
on: [pull_request]
jobs:
  junits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: corretto
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-results
          path: build/test-results/test/
